const RAW_PLAYERS = [
  { id: 1, name: "HAALAND", nationality: "Norveç", club: "Manchester City", category: "yabanci_yeni", hasSpace: false },
  { id: 2, name: "MBAPPE", nationality: "Fransa", club: "Real Madrid", category: "yabanci_yeni", hasSpace: false },
  { id: 3, name: "SALAH", nationality: "Mısır", club: "Liverpool", category: "yabanci_yeni", hasSpace: false },
  { id: 4, name: "BELLINGHAM", nationality: "İngiltere", club: "Real Madrid", category: "yabanci_yeni", hasSpace: false },
  { id: 5, name: "OSIMHEN", nationality: "Nijerya", club: "Galatasaray", category: "yabanci_yeni", hasSpace: false },
  { id: 6, name: "MUSIALA", nationality: "Almanya", club: "Bayern Münih", category: "yabanci_yeni", hasSpace: false },
  { id: 7, name: "LAUTARO", nationality: "Arjantin", club: "Inter", category: "yabanci_yeni", hasSpace: false },
  { id: 8, name: "YAMAL", nationality: "İspanya", club: "Barcelona", category: "yabanci_yeni", hasSpace: false },
  { id: 9, name: "KANE", nationality: "İngiltere", club: "Bayern Münih", category: "yabanci_yeni", hasSpace: false },
  { id: 10, name: "VINICIUS", nationality: "Brezilya", club: "Real Madrid", category: "yabanci_yeni", hasSpace: false },
  { id: 11, name: "RODRI", nationality: "İspanya", club: "Manchester City", category: "yabanci_yeni", hasSpace: false },
  { id: 12, name: "WIRTZ", nationality: "Almanya", club: "Bayer Leverkusen", category: "yabanci_yeni", hasSpace: false },
  { id: 13, name: "PALMER", nationality: "İngiltere", club: "Chelsea", category: "yabanci_yeni", hasSpace: false },
  { id: 14, name: "VALVERDE", nationality: "Uruguay", club: "Real Madrid", category: "yabanci_yeni", hasSpace: false },
  { id: 15, name: "SAKA", nationality: "İngiltere", club: "Arsenal", category: "yabanci_yeni", hasSpace: false },
  { id: 16, name: "FODEN", nationality: "İngiltere", club: "Manchester City", category: "yabanci_yeni", hasSpace: false },
  { id: 17, name: "LEWANDOWSKI", nationality: "Polonya", club: "Barcelona", category: "yabanci_yeni", hasSpace: false },
  { id: 18, name: "DEBRUYNE", nationality: "Belçika", club: "Manchester City", category: "yabanci_yeni", hasSpace: false },
  { id: 19, name: "VAN DIJK", nationality: "Hollanda", club: "Liverpool", category: "yabanci_yeni", hasSpace: true },
  { id: 20, name: "SON", nationality: "Güney Kore", club: "Tottenham", category: "yabanci_yeni", hasSpace: false },
  { id: 21, name: "SALIBA", nationality: "Fransa", club: "Arsenal", category: "yabanci_yeni", hasSpace: false },
  { id: 22, name: "GRIEZMANN", nationality: "Fransa", club: "Atletico Madrid", category: "yabanci_yeni", hasSpace: false },
  { id: 23, name: "RICE", nationality: "İngiltere", club: "Arsenal", category: "yabanci_yeni", hasSpace: false },
  { id: 24, name: "LEAO", nationality: "Portekiz", club: "Milan", category: "yabanci_yeni", hasSpace: false },
  { id: 25, name: "OBLAK", nationality: "Slovenya", club: "Atletico Madrid", category: "yabanci_yeni", hasSpace: false },
  { id: 26, name: "DONNARUMMA", nationality: "İtalya", club: "PSG", category: "yabanci_yeni", hasSpace: false },
  { id: 27, name: "ALVAREZ", nationality: "Arjantin", club: "Atletico Madrid", category: "yabanci_yeni", hasSpace: false },
  { id: 28, name: "GYOKERES", nationality: "İsveç", club: "Sporting CP", category: "yabanci_yeni", hasSpace: false },
  { id: 29, name: "SANE", nationality: "Almanya", club: "Bayern Münih", category: "yabanci_yeni", hasSpace: false },
  { id: 30, name: "DIAS", nationality: "Portekiz", club: "Manchester City", category: "yabanci_yeni", hasSpace: false },
  { id: 31, name: "GAKPO", nationality: "Hollanda", club: "Liverpool", category: "yabanci_yeni", hasSpace: false },
  { id: 32, name: "MAHREZ", nationality: "Cezayir", club: "Al Ahli", category: "yabanci_yeni", hasSpace: false },
  { id: 33, name: "MANE", nationality: "Senegal", club: "Al Nassr", category: "yabanci_yeni", hasSpace: false },
  { id: 34, name: "DEMBELE", nationality: "Fransa", club: "PSG", category: "yabanci_yeni", hasSpace: false },
  { id: 35, name: "KVARATSKHELIA", nationality: "Gürcistan", club: "Napoli", category: "yabanci_yeni", hasSpace: false },
  { id: 36, name: "DYBALA", nationality: "Arjantin", club: "Roma", category: "yabanci_yeni", hasSpace: false },
  { id: 37, name: "CHESA", nationality: "İtalya", club: "Liverpool", category: "yabanci_yeni", hasSpace: false },
  { id: 38, name: "MENDY", nationality: "Fransa", club: "Real Madrid", category: "yabanci_yeni", hasSpace: false },
  { id: 39, name: "BARELLA", nationality: "İtalya", club: "Inter", category: "yabanci_yeni", hasSpace: false },
  { id: 40, name: "GVARDIOL", nationality: "Hırvatistan", club: "Manchester City", category: "yabanci_yeni", hasSpace: false },
  { id: 41, name: "HAKIMI", nationality: "Fas", club: "PSG", category: "yabanci_yeni", hasSpace: false },
  { id: 42, name: "TSYGANKOV", nationality: "Ukrayna", club: "Girona", category: "yabanci_yeni", hasSpace: false },
  { id: 43, name: "DE LIGT", nationality: "Hollanda", club: "Manchester United", category: "yabanci_yeni", hasSpace: true },
  { id: 44, name: "FERNANDES", nationality: "Portekiz", club: "Manchester United", category: "yabanci_yeni", hasSpace: false },
  { id: 45, name: "LUKAKU", nationality: "Belçika", club: "Napoli", category: "yabanci_yeni", hasSpace: false },
  { id: 46, name: "UPAMECANO", nationality: "Fransa", club: "Bayern Münih", category: "yabanci_yeni", hasSpace: false },
  { id: 47, name: "XHAKA", nationality: "İsviçre", club: "Bayer Leverkusen", category: "yabanci_yeni", hasSpace: false },
  { id: 48, name: "SCHICK", nationality: "Çekya", club: "Bayer Leverkusen", category: "yabanci_yeni", hasSpace: false },
  { id: 49, name: "MORATA", nationality: "İspanya", club: "Milan", category: "yabanci_yeni", hasSpace: false },
  { id: 50, name: "BONIFACE", nationality: "Nijerya", club: "Bayer Leverkusen", category: "yabanci_yeni", hasSpace: false },
  { id: 51, name: "MESSI", nationality: "Arjantin", club: "Inter Miami", category: "yabanci_eski", hasSpace: false },
  { id: 52, name: "RONALDO", nationality: "Portekiz", club: "Al Nassr", category: "yabanci_eski", hasSpace: false },
  { id: 53, name: "ZIDANE", nationality: "Fransa", club: "Real Madrid / Juventus", category: "yabanci_eski", hasSpace: false },
  { id: 54, name: "MARADONA", nationality: "Arjantin", club: "Napoli / Barcelona", category: "yabanci_eski", hasSpace: false },
  { id: 55, name: "PELE", nationality: "Brezilya", club: "Santos", category: "yabanci_eski", hasSpace: false },
  { id: 56, name: "CRUYFF", nationality: "Hollanda", club: "Ajax / Barcelona", category: "yabanci_eski", hasSpace: false },
  { id: 57, name: "RONALDINHO", nationality: "Brezilya", club: "Barcelona / Milan", category: "yabanci_eski", hasSpace: false },
  { id: 58, name: "KAKA", nationality: "Brezilya", club: "Milan / Real Madrid", category: "yabanci_eski", hasSpace: false },
  { id: 59, name: "HENRY", nationality: "Fransa", club: "Arsenal / Barcelona", category: "yabanci_eski", hasSpace: false },
  { id: 60, name: "INIESTA", nationality: "İspanya", club: "Barcelona", category: "yabanci_eski", hasSpace: false },
  { id: 61, name: "XAVI", nationality: "İspanya", club: "Barcelona", category: "yabanci_eski", hasSpace: false },
  { id: 62, name: "MALDIRE", nationality: "İtalya", club: "Milan", category: "yabanci_eski", hasSpace: false },
  { id: 63, name: "PIRLO", nationality: "İtalya", club: "Milan / Juventus", category: "yabanci_eski", hasSpace: false },
  { id: 64, name: "BUFFON", nationality: "İtalya", club: "Juventus / Parma", category: "yabanci_eski", hasSpace: false },
  { id: 65, name: "Ibrahimovic", nationality: "İsveç", club: "Milan / PSG / Inter", category: "yabanci_eski", hasSpace: false },
  { id: 66, name: "ROONEY", nationality: "İngiltere", club: "Manchester United", category: "yabanci_eski", hasSpace: false },
  { id: 67, name: "BECKHAM", nationality: "İngiltere", club: "Manchester United / Real Madrid", category: "yabanci_eski", hasSpace: false },
  { id: 68, name: "GERRARD", nationality: "İngiltere", club: "Liverpool", category: "yabanci_eski", hasSpace: false },
  { id: 69, name: "LAMPARD", nationality: "İngiltere", club: "Chelsea", category: "yabanci_eski", hasSpace: false },
  { id: 70, name: "DROGBA", nationality: "Fildişi Sahili", club: "Chelsea / Galatasaray", category: "yabanci_eski", hasSpace: false },
  { id: 71, name: "ETO", nationality: "Kamerun", club: "Barcelona / Inter / Antalyaspor", category: "yabanci_eski", hasSpace: false },
  { id: 72, name: "SNEYDER", nationality: "Hollanda", club: "Inter / Galatasaray / Real Madrid", category: "yabanci_eski", hasSpace: false },
  { id: 73, name: "ROBBEN", nationality: "Hollanda", club: "Bayern Münih / Real Madrid", category: "yabanci_eski", hasSpace: false },
  { id: 74, name: "RIBERY", nationality: "Fransa", club: "Bayern Münih / Galatasaray", category: "yabanci_eski", hasSpace: false },
  { id: 75, name: "SUAREZ", nationality: "Uruguay", club: "Barcelona / Liverpool", category: "yabanci_eski", hasSpace: false },
  { id: 76, name: "NEYMAR", nationality: "Brezilya", club: "Barcelona / PSG", category: "yabanci_eski", hasSpace: false },
  { id: 77, name: "BALE", nationality: "Galler", club: "Real Madrid / Tottenham", category: "yabanci_eski", hasSpace: false },
  { id: 78, name: "AGUERO", nationality: "Arjantin", club: "Manchester City / Atletico Madrid", category: "yabanci_eski", hasSpace: false },
  { id: 79, name: "PUYOL", nationality: "İspanya", club: "Barcelona", category: "yabanci_eski", hasSpace: false },
  { id: 80, name: "RAMOS", nationality: "İspanya", club: "Real Madrid / PSG", category: "yabanci_eski", hasSpace: false },
  { id: 81, name: "CASILLAS", nationality: "İspanya", club: "Real Madrid", category: "yabanci_eski", hasSpace: false },
  { id: 82, name: "NEUER", nationality: "Almanya", club: "Bayern Münih", category: "yabanci_eski", hasSpace: false },
  { id: 83, name: "MULLER", nationality: "Almanya", club: "Bayern Münih", category: "yabanci_eski", hasSpace: false },
  { id: 84, name: "OZIL", nationality: "Almanya", club: "Real Madrid / Arsenal / Fenerbahçe", category: "yabanci_eski", hasSpace: false },
  { id: 85, name: "KROOS", nationality: "Almanya", club: "Real Madrid / Bayern Münih", category: "yabanci_eski", hasSpace: false },
  { id: 86, name: "MODRIC", nationality: "Hırvatistan", club: "Real Madrid / Tottenham", category: "yabanci_eski", hasSpace: false },
  { id: 87, name: "BENZEMA", nationality: "Fransa", club: "Real Madrid / Al Ittihad", category: "yabanci_eski", hasSpace: false },
  { id: 88, name: "POGBA", nationality: "Fransa", club: "Juventus / Manchester United", category: "yabanci_eski", hasSpace: false },
  { id: 89, name: "HAZARD", nationality: "Belçika", club: "Chelsea / Real Madrid", category: "yabanci_eski", hasSpace: false },
  { id: 90, name: "CHIELLINI", nationality: "İtalya", club: "Juventus", category: "yabanci_eski", hasSpace: false },
  { id: 91, name: "SHEVCHENKO", nationality: "Ukrayna", club: "Milan / Chelsea", category: "yabanci_eski", hasSpace: false },
  { id: 92, name: "NEDVED", nationality: "Çekya", club: "Juventus / Lazio", category: "yabanci_eski", hasSpace: false },
  { id: 93, name: "DEL PIERO", nationality: "İtalya", club: "Juventus", category: "yabanci_eski", hasSpace: true },
  { id: 94, name: "TOTTI", nationality: "İtalya", club: "Roma", category: "yabanci_eski", hasSpace: false },
  { id: 95, name: "FIGO", nationality: "Portekiz", club: "Real Madrid / Barcelona / Inter", category: "yabanci_eski", hasSpace: false },
  { id: 96, name: "RIVALDO", nationality: "Brezilya", club: "Barcelona / Milan", category: "yabanci_eski", hasSpace: false },
  { id: 97, name: "BERGKAMP", nationality: "Hollanda", club: "Arsenal / Inter", category: "yabanci_eski", hasSpace: false },
  { id: 98, name: "KLOSE", nationality: "Almanya", club: "Bayern Münih / Lazio", category: "yabanci_eski", hasSpace: false },
  { id: 99, name: "CANNAVARO", nationality: "İtalya", club: "Juventus / Real Madrid", category: "yabanci_eski", hasSpace: false },
  { id: 100, name: "REYES", nationality: "İspanya", club: "Arsenal / Sevilla", category: "yabanci_eski", hasSpace: false },
  { id: 101, name: "ARDA GULER", nationality: "Türkiye", club: "Real Madrid", category: "turk_yeni", hasSpace: true },
  { id: 102, name: "HAKAN CALHANOGLU", nationality: "Türkiye", club: "Inter", category: "turk_yeni", hasSpace: true },
  { id: 103, name: "KENAN YILDIZ", nationality: "Türkiye", club: "Juventus", category: "turk_yeni", hasSpace: true },
  { id: 104, name: "KEREM AKTURKOGLU", nationality: "Türkiye", club: "Benfica", category: "turk_yeni", hasSpace: true },
  { id: 105, name: "BARIS ALPER YILMAZ", nationality: "Türkiye", club: "Galatasaray", category: "turk_yeni", hasSpace: true },
  { id: 106, name: "FERDI KADIOGLU", nationality: "Türkiye", club: "Brighton", category: "turk_yeni", hasSpace: true },
  { id: 107, name: "SEMİH KILICSOY", nationality: "Türkiye", club: "Beşiktaş", category: "turk_yeni", hasSpace: true },
  { id: 108, name: "ABDULKERIM BARDAKCI", nationality: "Türkiye", club: "Galatasaray", category: "turk_yeni", hasSpace: true },
  { id: 109, name: "MERİH DEMIRAL", nationality: "Türkiye", club: "Al Ahli", category: "turk_yeni", hasSpace: true },
  { id: 110, name: "CAGLAR SOYUNCU", nationality: "Türkiye", club: "Fenerbahçe", category: "turk_yeni", hasSpace: true },
  { id: 111, name: "OKAN BURUK", nationality: "Türkiye", club: "Galatasaray / Inter", category: "turk_eski", hasSpace: true },
  { id: 112, name: "SERGEN YALCIN", nationality: "Türkiye", club: "Beşiktaş / Galatasaray / Fenerbahçe", category: "turk_eski", hasSpace: true },
  { id: 113, name: "ARDA TURAN", nationality: "Türkiye", club: "Atletico Madrid / Barcelona / Galatasaray", category: "turk_eski", hasSpace: true },
  { id: 114, name: "BURAK YILMAZ", nationality: "Türkiye", club: "Lille / Trabzonspor / Galatasaray", category: "turk_eski", hasSpace: true },
  { id: 115, name: "CENK TOSUN", nationality: "Türkiye", club: "Everton / Beşiktaş / Fenerbahçe", category: "turk_yeni", hasSpace: true },
  { id: 116, name: "UGURCAN CAKIR", nationality: "Türkiye", club: "Trabzonspor", category: "turk_yeni", hasSpace: true },
  { id: 117, name: "ALTAY BAYINDIR", nationality: "Türkiye", club: "Manchester United / Fenerbahçe", category: "turk_yeni", hasSpace: true },
  { id: 118, name: "IRFAN CAN KAHVECI", nationality: "Türkiye", club: "Fenerbahçe / Başakşehir", category: "turk_yeni", hasSpace: true },
  { id: 119, name: "CENGIZ UNDER", nationality: "Türkiye", club: "Roma / Marsilya / Fenerbahçe", category: "turk_yeni", hasSpace: true },
  { id: 120, name: "YUSUF YAZICI", nationality: "Türkiye", club: "Lille / Trabzonspor / Olympiakos", category: "turk_yeni", hasSpace: true },
  { id: 121, name: "OKAY YOKUSLU", nationality: "Türkiye", club: "Celta Vigo / Trabzonspor", category: "turk_yeni", hasSpace: true },
  { id: 122, name: "SALİH OZCAN", nationality: "Türkiye", club: "Dortmund / Wolfsburg", category: "turk_yeni", hasSpace: true },
  { id: 123, name: "ORKUN KOKCU", nationality: "Türkiye", club: "Benfica / Feyenoord", category: "turk_yeni", hasSpace: true },
  { id: 124, name: "ZEKİ CELIK", nationality: "Türkiye", club: "Roma / Lille", category: "turk_yeni", hasSpace: true },
  { id: 125, name: "KAAN AYHAN", nationality: "Türkiye", club: "Sassuolo / Galatasaray", category: "turk_yeni", hasSpace: true },
  { id: 126, name: "OZAN KABAK", nationality: "Türkiye", club: "Hoffenheim / Liverpool / Schalke", category: "turk_yeni", hasSpace: true },
  { id: 127, name: "EREN ELMALI", nationality: "Türkiye", club: "Trabzonspor", category: "turk_yeni", hasSpace: true },
  { id: 128, name: "SAMET AKAYDIN", nationality: "Türkiye", club: "Fenerbahçe / Panathinaikos", category: "turk_yeni", hasSpace: true },
  { id: 129, name: "CAN UZUN", nationality: "Türkiye", club: "Eintracht Frankfurt / Nürnberg", category: "turk_yeni", hasSpace: true },
  { id: 130, name: "YUNUS AKGUN", nationality: "Türkiye", club: "Galatasaray / Leicester", category: "turk_yeni", hasSpace: true },
  { id: 131, name: "BERKAN KUTLU", nationality: "Türkiye", club: "Galatasaray / Genoa", category: "turk_yeni", hasSpace: true },
  { id: 132, name: "UMUT NAYIR", nationality: "Türkiye", club: "Konyaspor / Fenerbahçe", category: "turk_yeni", hasSpace: true },
  { id: 133, name: "DENIZ UNDAV", nationality: "Almanya / Türkiye", club: "Stuttgart / Brighton", category: "turk_yeni", hasSpace: true },
  { id: 134, name: "BERKAY OZCAN", nationality: "Türkiye", club: "Başakşehir", category: "turk_yeni", hasSpace: true },
  { id: 135, name: "EMRE MOR", nationality: "Türkiye", club: "Dortmund / Celta Vigo / Eyüpspor", category: "turk_yeni", hasSpace: true },
  { id: 136, name: "SERDAR AZIZ", nationality: "Türkiye", club: "Fenerbahçe / Galatasaray / Bursaspor", category: "turk_yeni", hasSpace: true },
  { id: 137, name: "NECIP UYSAL", nationality: "Türkiye", club: "Beşiktaş", category: "turk_yeni", hasSpace: true },
  { id: 138, name: "RIDVAN YILMAZ", nationality: "Türkiye", club: "Rangers / Beşiktaş", category: "turk_yeni", hasSpace: true },
  { id: 139, name: "MERT GUNOK", nationality: "Türkiye", club: "Beşiktaş / Başakşehir / Fenerbahçe", category: "turk_yeni", hasSpace: true },
  { id: 140, name: "MERT MULDUR", nationality: "Türkiye", club: "Fenerbahçe / Sassuolo", category: "turk_yeni", hasSpace: true },
  { id: 141, name: "UMUT MERAS", nationality: "Türkiye", club: "Samsunspor / Beşiktaş / Le Havre", category: "turk_yeni", hasSpace: true },
  { id: 142, name: "TAYLAN ANTALYALI", nationality: "Türkiye", club: "Galatasaray / Bodrum FK", category: "turk_yeni", hasSpace: true },
  { id: 143, name: "EFECAN KARACA", nationality: "Türkiye", club: "Alanyaspor", category: "turk_yeni", hasSpace: true },
  { id: 144, name: "DORUKHAN TOKOZ", nationality: "Türkiye", club: "Beşiktaş / Trabzonspor / Eyüpspor", category: "turk_yeni", hasSpace: true },
  { id: 145, name: "HALIL DERVISOGLU", nationality: "Türkiye", club: "Galatasaray / Brentford", category: "turk_yeni", hasSpace: true },
  { id: 146, name: "SERDAR DURSUN", nationality: "Türkiye", club: "Fenerbahçe / Darmstadt", category: "turk_yeni", hasSpace: true },
  { id: 147, name: "BERAT OZDEMIR", nationality: "Türkiye", club: "Trabzonspor / Al Ettifaq", category: "turk_yeni", hasSpace: true },
  { id: 148, name: "OZAN TUFAN", nationality: "Türkiye", club: "Trabzonspor / Hull City / Fenerbahçe", category: "turk_yeni", hasSpace: true },
  { id: 149, name: "EMRE CAN", nationality: "Almanya / Türkiye", club: "Dortmund / Juventus / Liverpool", category: "turk_yeni", hasSpace: true },
  { id: 150, name: "SALIH UCAN", nationality: "Türkiye", club: "Beşiktaş / Roma / Alanyaspor", category: "turk_yeni", hasSpace: true },
  { id: 151, name: "RUSTU RECBER", nationality: "Türkiye", club: "Fenerbahçe / Barcelona / Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 152, name: "HAKAN SUKUR", nationality: "Türkiye", club: "Galatasaray / Inter / Torino", category: "turk_eski", hasSpace: true },
  { id: 153, name: "BULENT KORKMAZ", nationality: "Türkiye", club: "Galatasaray", category: "turk_eski", hasSpace: true },
  { id: 154, name: "TUGAY KERIMOGLU", nationality: "Türkiye", club: "Blackburn Rovers / Galatasaray", category: "turk_eski", hasSpace: true },
  { id: 155, name: "NIHAT KAHVECI", nationality: "Türkiye", club: "Real Sociedad / Villarreal / Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 156, name: "HAMIT ALTINTOP", nationality: "Türkiye", club: "Bayern Münih / Real Madrid / Schalke", category: "turk_eski", hasSpace: true },
  { id: 157, name: "HALIL ALTINTOP", nationality: "Türkiye", club: "Schalke / Frankfurt / Trabzonspor", category: "turk_eski", hasSpace: true },
  { id: 158, name: "ILKAY GUNDOGAN", nationality: "Almanya / Türkiye", club: "Manchester City / Barcelona", category: "turk_eski", hasSpace: true },
  { id: 159, name: "NURI SAHIN", nationality: "Türkiye", club: "Dortmund / Real Madrid / Liverpool", category: "turk_eski", hasSpace: true },
  { id: 160, name: "EMRE BELOZOGLU", nationality: "Türkiye", club: "Inter / Newcastle / Fenerbahçe", category: "turk_eski", hasSpace: true },
  { id: 161, name: "METIN OKTAY", nationality: "Türkiye", club: "Galatasaray / Palermo", category: "turk_eski", hasSpace: true },
  { id: 162, name: "LEFTER KUCUKANDONYADIS", nationality: "Türkiye", club: "Fenerbahçe / Fiorentina", category: "turk_eski", hasSpace: true },
  { id: 163, name: "TANJU COLAK", nationality: "Türkiye", club: "Galatasaray / Fenerbahçe / Samsunspor", category: "turk_eski", hasSpace: true },
  { id: 164, name: "RIDVAN DILMEN", nationality: "Türkiye", club: "Fenerbahçe / Sarıyer", category: "turk_eski", hasSpace: true },
  { id: 165, name: "HASAN SAS", nationality: "Türkiye", club: "Galatasaray", category: "turk_eski", hasSpace: true },
  { id: 166, name: "UMIT DAVALA", nationality: "Türkiye", club: "Werder Bremen / Milan / Galatasaray", category: "turk_eski", hasSpace: true },
  { id: 167, name: "ILHAN MANSIZ", nationality: "Türkiye", club: "Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 168, name: "ALPAY OZALAN", nationality: "Türkiye", club: "Aston Villa / Köln / Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 169, name: "YILDIRAY BASTURK", nationality: "Türkiye", club: "Bayer Leverkusen / Stuttgart", category: "turk_eski", hasSpace: true },
  { id: 170, name: "SELUK INAN", nationality: "Türkiye", club: "Galatasaray / Trabzonspor", category: "turk_eski", hasSpace: true },
  { id: 171, name: "VOLKAN DEMIREL", nationality: "Türkiye", club: "Fenerbahçe", category: "turk_eski", hasSpace: true },
  { id: 172, name: "SABRI SARIOGLU", nationality: "Türkiye", club: "Galatasaray", category: "turk_eski", hasSpace: true },
  { id: 173, name: "GOKHAN GONUL", nationality: "Türkiye", club: "Fenerbahçe / Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 174, name: "CANER ERKIN", nationality: "Türkiye", club: "CSKA Moskova / Fenerbahçe / Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 175, name: "HAMI MANDIRALI", nationality: "Türkiye", club: "Trabzonspor / Schalke", category: "turk_eski", hasSpace: true },
  { id: 176, name: "FATIH TERIM", nationality: "Türkiye", club: "Galatasaray / Adana Demirspor", category: "turk_eski", hasSpace: true },
  { id: 177, name: "SENOL GUNES", nationality: "Türkiye", club: "Trabzonspor", category: "turk_eski", hasSpace: true },
  { id: 178, name: "MUSTAFA DENIZLI", nationality: "Türkiye", club: "Altay / Galatasaray", category: "turk_eski", hasSpace: true },
  { id: 179, name: "OGUZ CETIN", nationality: "Türkiye", club: "Fenerbahçe / İstanbulspor", category: "turk_eski", hasSpace: true },
  { id: 180, name: "AYKUT KOCAMAN", nationality: "Türkiye", club: "Fenerbahçe / Sakaryaspor", category: "turk_eski", hasSpace: true },
  { id: 181, name: "FATIH TEKKE", nationality: "Türkiye", club: "Zenit / Trabzonspor", category: "turk_eski", hasSpace: true },
  { id: 182, name: "GOKDENIZ KARADENIZ", nationality: "Türkiye", club: "Rubin Kazan / Trabzonspor", category: "turk_eski", hasSpace: true },
  { id: 183, name: "MEHMET TOPAL", nationality: "Türkiye", club: "Valencia / Fenerbahçe / Galatasaray", category: "turk_eski", hasSpace: true },
  { id: 184, name: "EGEMEN KORKMAZ", nationality: "Türkiye", club: "Trabzonspor / Fenerbahçe / Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 185, name: "NECATI ATES", nationality: "Türkiye", club: "Galatasaray / Antalyaspor", category: "turk_eski", hasSpace: true },
  { id: 186, name: "UMIT KARAN", nationality: "Türkiye", club: "Galatasaray / Gençlerbirliği", category: "turk_eski", hasSpace: true },
  { id: 187, name: "BATUHAN KARADENIZ", nationality: "Türkiye", club: "Beşiktaş / Eskişehirspor", category: "turk_eski", hasSpace: true },
  { id: 188, name: "MEHMET OZDILEK", nationality: "Türkiye", club: "Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 189, name: "RIZA CALIMBAY", nationality: "Türkiye", club: "Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 190, name: "FEYYAZ UAR", nationality: "Türkiye", club: "Beşiktaş / Fenerbahçe", category: "turk_eski", hasSpace: true },
  { id: 191, name: "ALI GULTIKEN", nationality: "Türkiye", club: "Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 192, name: "METIN TEKIN", nationality: "Türkiye", club: "Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 193, name: "CAN BARTU", nationality: "Türkiye", club: "Fenerbahçe / Fiorentina", category: "turk_eski", hasSpace: true },
  { id: 194, name: "HAKKI YETEN", nationality: "Türkiye", club: "Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 195, name: "SULEYMAN SEBA", nationality: "Türkiye", club: "Beşiktaş", category: "turk_eski", hasSpace: true },
  { id: 196, name: "TUNCAY SANLI", nationality: "Türkiye", club: "Middlesbrough / Stoke City / Fenerbahçe", category: "turk_eski", hasSpace: true },
  { id: 197, name: "SEMIH SENTURK", nationality: "Türkiye", club: "Fenerbahçe", category: "turk_eski", hasSpace: true },
  { id: 198, name: "SERHAT AKIN", nationality: "Türkiye", club: "Anderlecht / Fenerbahçe", category: "turk_eski", hasSpace: true },
  { id: 199, name: "SUREYYA AYHAN", nationality: "Türkiye", club: "Atletizm / Futbol Kültürü", category: "turk_eski", hasSpace: true },
  { id: 200, name: "GOKHAN INLER", nationality: "İsviçre / Türkiye", club: "Napoli / Leicester / Beşiktaş", category: "turk_eski", hasSpace: true },
];

function normalizeName(name) {
  return name.trim().replace(/\s+/g, " ").toUpperCase();
}

const EASY_PLAYER_NAMES = new Set([
  "HAALAND",
  "MBAPPE",
  "SALAH",
  "KANE",
  "MESSI",
  "RONALDO",
  "NEYMAR",
  "PELE",
  "XAVI",
  "KAKA",
  "HENRY",
  "MUSIALA",
  "VINICIUS",
  "ARDA GULER",
  "HAKAN CALHANOGLU",
  "KENAN YILDIZ",
  "ARDA TURAN",
  "BURAK YILMAZ",
  "CENK TOSUN",
  "OKAN BURUK",
  "RUSTU RECBER",
  "FATIH TERIM",
]);

const HARD_PLAYER_NAMES = new Set([
  "KVARATSKHELIA",
  "TSYGANKOV",
  "UPAMECANO",
  "LEWANDOWSKI",
  "DONNARUMMA",
  "BELLINGHAM",
  "SHEVCHENKO",
  "CANNAVARO",
  "LEFTER KUCUKANDONYADIS",
  "ABDULKERIM BARDAKCI",
  "BARIS ALPER YILMAZ",
  "IRFAN CAN KAHVECI",
  "LEFTER KUCUKANDONYADIS",
  "GOKDENIZ KARADENIZ",
  "BATUHAN KARADENIZ",
  "TUGAY KERIMOGLU",
  "KVARATSKHELIA",
]);

function getPlayerDifficulty(name) {
  const cleanLength = name.replace(/\s/g, "").length;
  const wordCount = name.split(" ").length;

  if (HARD_PLAYER_NAMES.has(name)) {
    return "hard";
  }

  if (EASY_PLAYER_NAMES.has(name) || (cleanLength <= 6 && wordCount === 1)) {
    return "easy";
  }

  if (cleanLength >= 11 || wordCount >= 3) {
    return "hard";
  }

  return "medium";
}

export const PLAYER_DATA = RAW_PLAYERS.map((player) => {
  const name = normalizeName(player.name);

  return {
    ...player,
    name,
    difficulty: getPlayerDifficulty(name),
    hasSpace: name.includes(" "),
  };
});
